const httpStatusCodes: { [key: number]: string } = {
  100: 'The HTTP 100 Continue informational status response code indicates that the initial part of a request has been received and has not yet been rejected by the server.',
  101: "The HTTP 101 Switching Protocols informational status response code indicates that the server understands and is willing to comply with the client's request to switch protocols.",
  200: 'The HTTP 200 OK success status response code indicates that the request has succeeded.',
  201: 'The HTTP 201 Created success status response code indicates that the request has succeeded and has led to the creation of a resource.',
  202: 'The HTTP 202 Accepted status response code indicates that the request has been accepted for processing, but the processing has not been completed.',
  203: 'The HTTP 203 Non-Authoritative Information success status response code indicates that the request has succeeded, but the enclosed payload has been modified by a proxy.',
  204: "The HTTP 204 No Content success status response code indicates that the request has succeeded, but that the client doesn't need to navigate away from its current page.",
  205: 'The HTTP 205 Reset Content success status response code indicates that the request has succeeded and the user agent should reset the document view.',
  206: 'The HTTP 206 Partial Content success status response code indicates that the server is delivering only part of the resource due to a range header sent by the client.',
  300: 'The HTTP 300 Multiple Choices redirection response code indicates that the request has more than one possible response.',
  301: 'The HTTP 301 Moved Permanently redirection response code indicates that the requested resource has been assigned a new permanent URI.',
  302: 'The HTTP 302 Found redirection response code indicates that the resource requested has been temporarily moved to a different URI.',
  303: 'The HTTP 303 See Other redirection response code indicates that the server redirects the client to a different resource, using the GET method.',
  304: 'The HTTP 304 Not Modified redirection response code indicates that the resource has not been modified since the last request.',
  305: 'The HTTP 305 Use Proxy redirection response code indicates that the requested resource is available only through a proxy.',
  307: 'The HTTP 307 Temporary Redirect redirection response code indicates that the resource requested has been temporarily moved to a different URI.',
  308: 'The HTTP 308 Permanent Redirect redirection response code indicates that the resource requested has been permanently moved to a different URI.',
  400: 'The HTTP 400 Bad Request error response code indicates that the server cannot or will not process the request due to a client error.',
  401: 'The HTTP 401 Unauthorized client error response code indicates that the request has not been applied because it lacks valid authentication credentials.',
  402: 'The HTTP 402 Payment Required client error response code is reserved for future use.',
  403: 'The HTTP 403 Forbidden client error response code indicates that the server understands the request but refuses to authorize it.',
  404: "The HTTP 404 Not Found client error response code indicates that the server can't find the requested resource.",
  405: 'The HTTP 405 Method Not Allowed client error response code indicates that the method specified in the request is not allowed for the resource identified by the request URI.',
  406: "The HTTP 406 Not Acceptable client error response code indicates that the server cannot produce a response matching the list of acceptable values defined in the request's headers.",
  407: 'The HTTP 407 Proxy Authentication Required client error response code indicates that the client must first authenticate itself with the proxy.',
  408: 'The HTTP 408 Request Timeout client error response code indicates that the server timed out waiting for the request.',
  409: 'The HTTP 409 Conflict client error response code indicates that the request could not be completed due to a conflict with the current state of the resource.',
  410: 'The HTTP 410 Gone client error response code indicates that the resource requested is no longer available and will not be available again.',
  411: 'The HTTP 411 Length Required client error response code indicates that the server refuses to accept the request without a defined Content-Length header.',
  412: 'The HTTP 412 Precondition Failed client error response code indicates that one or more conditions in the request header fields evaluated to false when tested by the server.',
  413: 'The HTTP 413 Payload Too Large client error response code indicates that the request is larger than the server is willing or able to process.',
  414: 'The HTTP 414 URI Too Long client error response code indicates that the URI provided was too long for the server to process.',
  415: 'The HTTP 415 Unsupported Media Type client error response code indicates that the request entity has a media type which the server or resource does not support.',
  416: 'The HTTP 416 Range Not Satisfiable client error response code indicates that the server cannot serve the portion of the resource requested by the client.',
  417: 'The HTTP 417 Expectation Failed client error response code indicates that the server cannot meet the requirements of the Expect request-header field.',
  426: 'The HTTP 426 Upgrade Required client error response code indicates that the server refuses to perform the request using the current protocol but may be willing to do so if the client upgrades to a different protocol.',
  500: 'The HTTP 500 Internal Server Error server error response code indicates that the server encountered an unexpected condition that prevented it from fulfilling the request.',
  501: 'The HTTP 501 Not Implemented server error response code indicates that the server does not support the functionality required to fulfill the request.',
  502: 'The HTTP 502 Bad Gateway server error response code indicates that the server, while acting as a gateway or proxy, received an invalid response from the upstream server.',
  503: 'The HTTP 503 Service Unavailable server error response code indicates that the server is currently unable to handle the request due to temporary overloading or maintenance of the server.',
  504: 'The HTTP 504 Gateway Timeout server error response code indicates that the server, while acting as a gateway or proxy, did not receive a timely response from the upstream server or some other auxiliary server it needed to access in order to complete the request.',
  505: 'The HTTP 505 HTTP Version Not Supported server error response code indicates that the server does not support the HTTP protocol version that was used in the request.',
};

export default httpStatusCodes;
